### PR TITLE
allow user to pass preid to semver

### PR DESCRIPTION
**Pull request by scamden**
this makes it super easy to bump a version with a 'beta' tag in the version. trivial code change.

### CODE REVIEW

**Comment by stevelacy** [comment]
Rebase to squash commits.

**Comment by scamden** [comment]
@stevelacy squashed, do you really need a test for this? it's ultra basic

**Comment by stevelacy** [comment]
Thanks, I do like to have tests for all options. I can add it.

**Comment by stevelacy** [comment]
I'll publish and update tomorrow

**Comment by scamden** [comment]
Ok I get that, if you don't get to it tomorrow I'll try to, thanks for
merging!

**Pull request merged**
