### PR TITLE
add basic test for preid

### PR DESCRIPTION
**Pull request by scamden**
@stevelacy wrote a super basic test, let me know if you would want to do more

### CODE REVIEW

**Comment by stevelacy** [comment]
Oh my we wrote them at the same time!
I'll merge it in

**Comment by scamden** [comment]
haha! thanks man, thanks for the responsiveness! let me know when you bump so i can point back at the standard package!

**Comment by stevelacy** [comment]
@scamden published to 0.3.0

**Comment by scamden** [comment]
thanks!

**Pull request merged**
